org: igorkulishov
service: orders-apis

frameworkVersion: '2'

plugins:
  - serverless-mocha-plugin

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

  environment:
    DYNAMODB_PLACED_ORDERS_DETAILS: ${self:service}-${opt:stage, self:provider.stage}-placed-orders-details
    DYNAMODB_PLACED_ORDERS_DATES: ${self:service}-${opt:stage, self:provider.stage}-placed-orders-dates
    ACCESS_TOKEN_SECRET: 'secret.key'

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_PLACED_ORDERS_DETAILS}"
        - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_PLACED_ORDERS_DETAILS}/index/*"
        - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_PLACED_ORDERS_DATES}"
        - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_PLACED_ORDERS_DATES}/index/*"

functions:
  auth:
    handler: orders-auth/auth.auth

  create:
    handler: orders/create-user-order.create
    events:
      - http:
          path: orders
          method: post
          authorizer: auth
          cors: true
          integration: LAMBDA

  list:
    handler: orders/list-all-users-orders.list
    events:
      - http:
          path: orders
          method: get
          authorizer: auth
          cors: true
          integration: LAMBDA

  getByUserId:
    handler: orders/get-by-userid.getByUserId
    events:
      - http:
          path: orders/userid/{id}
          method: get
          authorizer: auth
          cors: true
          integration: LAMBDA

  getByOrderId:
    handler: orders/get-by-orderid.getByOrderId
    events:
      - http:
          path: orders/{id}
          method: get
          authorizer: auth
          cors: true
          integration: LAMBDA

  update:
    handler: orders/update-order.update
    events:
      - http:
          path: orders/{id}
          method: put
          authorizer: auth
          cors: true
          integration: LAMBDA

  delete:
    handler: orders/delete-order.delete
    events:
      - http:
          path: orders/delete
          method: post
          authorizer: auth
          cors: true
          integration: LAMBDA

  getOrderDatesByMonth:
    handler: orders/get-order-dates-by-month.getOrderDatesByMonth
    events:
      - http:
          path: order-date/{id}
          method: get
          authorizer: auth
          cors: true
          integration: LAMBDA

resources:
  Resources:
    GatewayResponseDefault4XX:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'http://localhost:4200'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: 'ApiGatewayRestApi'
    PlacedOrdersDetails:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: userid
            AttributeType: S
          - AttributeName: orderid
            AttributeType: S
          - AttributeName: orderPlacedDate
            AttributeType: S

        GlobalSecondaryIndexes:
          - IndexName: usersGSI
            KeySchema:
              - AttributeName: userid
                KeyType: HASH
            Projection:
              NonKeyAttributes:
                - orderDetails
                - orderStatus
                - updatedAt
              ProjectionType: INCLUDE
            ProvisionedThroughput:
              ReadCapacityUnits: '1'
              WriteCapacityUnits: '1'

          - IndexName: ordersDatesGSI
            KeySchema:
              - AttributeName: orderPlacedDate
                KeyType: HASH
            Projection:
              NonKeyAttributes:
                - orderDetails
                - orderStatus
                - updatedAt
              ProjectionType: INCLUDE
            ProvisionedThroughput:
              ReadCapacityUnits: '1'
              WriteCapacityUnits: '1'

          - IndexName: ordersGSI
            KeySchema:
              - AttributeName: orderid
                KeyType: HASH
            Projection:
              NonKeyAttributes:
                - orderDetails
                - orderStatus
              ProjectionType: INCLUDE
            ProvisionedThroughput:
              ReadCapacityUnits: '1'
              WriteCapacityUnits: '1'
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_PLACED_ORDERS_DETAILS}

    PlacedOrdersDates:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        KeySchema:
          - AttributeName: orderYearMonth
            KeyType: HASH
          - AttributeName: orderDay
            KeyType: RANGE
        AttributeDefinitions:
          - AttributeName: orderYearMonth
            AttributeType: S
          - AttributeName: orderDay
            AttributeType: S

        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_PLACED_ORDERS_DATES}
